# Copyright (C) 2018  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'

services:

    opendlv-cone-detection:
        image: registry.git.chalmers.se/courses/tme290/2021/group19/opendlv-cone-detection:v1.6
        restart: on-failure
        network_mode: "host"
        environment:
         - DISPLAY=${DISPLAY}
        ipc: "host"
        volumes:
         - /tmp:/tmp
        command: "--cid=140 --name=img.argb --width=1280 --height=720 --freq=50 --strategy=2" 

    opendlv-kiwi-control:
        image: registry.git.chalmers.se/courses/tme290/2021/group19/opendlv-kiwi-control:v1.3
        network_mode: "host"
        command: "/usr/bin/opendlv-image-processing2 --cid=140 --freq=70 --frame-id=0 --Vmax=0.2 "
        


